# --------------------------------------
# Author: Andreas Alfons
#         Erasmus Universiteit Rotterdam
# --------------------------------------


## function to write style file, either to R console or to an actual file
#' @export

r2spss.sty <- function(path = ".") {

  # determine file name
  if (is.null(path)) file <- ""  # write to standard output (usually R console)
  else {
    sep <- if (endsWith(path, "/")) "" else "/"
    fileName <- paste(path, "r2spss.sty", sep = sep)
    file <- file(fileName, open = "w")
    on.exit(close(file))
  }

  # write author information
  cat("% ----------------------------------------------------------\n",
      file = file)
  cat("% Author: Andreas Alfons\n", file = file)
  cat("%         Erasmus University Rotterdam\n", file = file)
  cat("% \n", file = file)
  cat("% Generated by function r2spss.sty() from R package 'r2spss'\n",
      file = file)
  cat("% ----------------------------------------------------------\n\n",
      file = file)

  # write package identification
  cat("\\NeedsTeXFormat{LaTeX2e}\n", file = file)
  cat("\\ProvidesPackage{r2spss}%\n", file = file)
  cat("[", as.character(packageDate("r2spss"), format = "%Y/%m/%d"),
      " Format R Output to Look Like SPSS v",
      as.character(packageVersion("r2spss")), "]\n\n",
      file = file, sep = "")

  # write LaTeX statements for required packages
  cat("% additional packages\n", file = file)
  cat("\\RequirePackage{amsmath}\n", file = file)
  cat("\\RequirePackage{array}\n", file = file)
  cat("\\RequirePackage{colortbl}\n", file = file)
  cat("\\RequirePackage[T1]{fontenc}\n\n", file = file)

  # write LaTeX statements to define colors
  cat("% define colors\n", file = file)
  cat("\\definecolor{graySPSS}{gray}{0.87}\n", file = file)
  cat("\\definecolor{lightgraySPSS}{RGB}{250,250,252}\n", file = file,
      append = TRUE)
  cat("\\definecolor{darkgraySPSS}{gray}{0.66}\n", file = file)
  cat("\\definecolor{blueSPSS}{RGB}{39,73,96}\n\n", file = file)

  # write LaTeX statements to define new column types for tabular environment
  cat("% new column types for tabular environment\n", file = file)
  cat("\\newcolumntype{L}[1]{>{\\raggedright\\let\\newline\\\\\\arraybackslash\\hspace{0pt}}m{#1}}\n",
      file = file)
  cat("\\newcolumntype{C}[1]{>{\\centering\\let\\newline\\\\\\arraybackslash\\hspace{0pt}}m{#1}}\n",
      file = file)
  cat("\\newcolumntype{R}[1]{>{\\raggedleft\\let\\newline\\\\\\arraybackslash\\hspace{0pt}}m{#1}}\n",
      file = file)

}
